apiVersion: v1
kind: Service
metadata:
  name: date-suggestions
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  selector:
    app: date-suggestions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000